@echo off
rem --------------------- GITIGNORE ------------------
@echo ## Ignore Visual Studio temporary files, build results, and > .gitignore
@echo ## files generated by popular Visual Studio add-ons.>> .gitignore
rem The dot after 'echo' below means 'dont output the echo command, just print a newline"
@echo.>> .gitignore 
@echo # User-specific files>> .gitignore
@echo *.suo>> .gitignore
@echo *.user>> .gitignore
@echo *.sln.docstates>> .gitignore
@echo.>> .gitignore 
@echo # Build results>> .gitignore
@echo [Dd]ebug/*>> .gitignore
@echo [Bb]in/*>> .gitignore
@echo [Oo]bj/*>> .gitignore
@echo [Pp]rivate/*>> .gitignore
@echo.>> .gitignore
@echo # Leave the build hierarchy, but ignore the files in them>> .gitignore
@echo [Bb]uild/*>> .gitignore
@echo ![Bb]uild/app>> .gitignore
@echo ![Bb]uild/web>> .gitignore
@echo ![Bb]uild/console>> .gitignore
@echo ![Bb]uild/service>> .gitignore
@echo [Bb]uild/app/*>> .gitignore
@echo [Bb]uild/web/*>> .gitignore
@echo [Bb]uild/console/*>> .gitignore
@echo [Bb]uild/service/*>> .gitignore
@echo # Except ignore rules file>> .gitignore
@echo !.gitignore>> .gitignore
@echo.>> .gitignore
@echo *.obj>> .gitignore
@echo *.jar>> .gitignore
@echo # Except JARs in lib folder>> .gitignore
@echo !lib/*.jar>> .gitignore
@echo *.dll>> .gitignore
@echo # Except DLLs in lib folder>> .gitignore
@echo !lib/*.dll>> .gitignore
@echo *.pdb>> .gitignore
@echo *.vspscc>> .gitignore
@echo *.vssscc>> .gitignore
@echo *.vshost.exe.manifest>> .gitignore
@echo *.vshost.exe>> .gitignore
@echo *.class>> .gitignore
@echo *.[Cc]ache>> .gitignore
@echo *.refresh>> .gitignore
@echo.>> .gitignore
@echo Backup*/>> .gitignore
@echo UpgradeLog*.XML>> .gitignore
@echo UpgradeLog*.htm>> .gitignore
@echo.>> .gitignore
@echo # SQL Server files>> .gitignore
@echo *.mdf>> .gitignore
@echo *.ldf>> .gitignore

rem ------------------------- README.MD ---------
@echo. > README.md

rem ------------------------- FOLDERS -----------
mkdir src 2>NUL >NUL
mkdir res\images 2>NUL >NUL
mkdir lib 2>NUL >NUL
mkdir docs\manuals 2>NUL >NUL
mkdir docs\specs 2>NUL >NUL
mkdir data\samples 2>NUL >NUL
mkdir data\scripts 2>NUL >NUL
mkdir build\app 2>NUL >NUL
mkdir build\console 2>NUL >NUL
mkdir build\web 2>NUL >NUL
mkdir build\service 2>NUL >NUL

rem ------------------- IGNORE FILES IN SUBFOLDERS ----------

@echo. > src\.gitignore
@echo *.dll>> src\.gitignore
@echo *.jar>> src\.gitignore
@echo. > res\.gitignore
@echo. > res\images\.gitignore
@echo. > lib\.gitignore
@echo. > docs\.gitignore
@echo. > docs\manuals\.gitignore
@echo. > docs\specs\.gitignore
@echo. > data\.gitignore
@echo. > data\samples\.gitignore
@echo. > data\scripts\.gitignore
@echo. > build\.gitignore
@echo. > build\app\.gitignore
@echo. > build\console\.gitignore
@echo. > build\web\.gitignore
@echo. > build\service\.gitignore



